### ISSUE TITLE
Swiping?

### ISSUE THREAD

**Issue by zam264** [zam264/CommonSquirrel#11]
Swiping for jumping supported

**Comment by WBotzer** [comment]
Should this be a setting that can be enabled/disabled or do we want this to be the primary method of tree hopping?

**Comment by zam264** [comment]
Definitely enabled or disabled, get more use out of our options screen.

**Comment by zgp1001** [comment]
Got swiping coded. Still need to add a thing to the option/pause menu. Already have a variable in option.lua that can control it (swipeMovement) - just need to add an option for the user that will alter the flag. 

--Also weird thing about swiping that I'll have to tell you guys about some time in person...

**Comment by zgp1001** [comment]
Added a button to Options. For some reason though the one I added to Pause doesn't work properly so its commented out for now. 

Also the button isn't very good looking. Its very small and gets pixelated when enlarged. We should probably look for a different one.

**Comment by WBotzer** [comment]
I think I fixed the last this issue, I'm gonna leave this open until more testing has been done.

**Comment by zgp1001** [comment]
Closing this as it seems rather complete now. 

If we find a bug we can reopen or make a bug post.
