### ISSUE TITLE
Life system

### ISSUE THREAD

**Issue by zam264** [zam264/CommonSquirrel#13]
Use nuts as life units

**Comment by WBotzer** [comment]
Some kind of life is currently implemented just not displayed. When your score stops increasing, you are out of life.

**Comment by zam264** [comment]
I was able to work off the previously implemented life system to add graphics that show decreasing health as collisions occur.  Issue will stay open until system is more robust and thoroughly tested.

**Comment by zam264** [comment]
-Add outline to health acorns
-Add screen flash when damage occurs
-Add damage squirrel sprite
-Add acorns that replenish health

**Comment by WBotzer** [comment]
Added a damage mask that fades in and out when the player gets hit.
