### ISSUE TITLE
Pause function

### ISSUE THREAD

**Issue by zam264** [zam264/CommonSquirrel#14]
We should probably have a way to pause the game during regular game-play.

Not sure if Will or Zach did this in Dungeon Crawler RPG

**Comment by zgp1001** [comment]
Agreed. In labyrinthian pausing was done by navigating to a different window. 

For this game a small pause button might be more practical. maybe this button also brings up the options screen (to adjust volume)?

**Comment by WBotzer** [comment]
A small pause button in the top right that would move to a new screen would be easy. Adding volume sliders is possible, they would need to change the options volume variable. Depending on how we do the background for the pause screen, we might need to hide the obstacles.

**Comment by zam264** [comment]
@WBotzer Are we still aiming to add these sliding options in the pause screen?  If not we can probably close out this issue.

**Comment by WBotzer** [comment]
They can be added easily if we still want them, so leave this open till the next time we discuss the app.
