### ISSUE TITLE
Scaling Difficulty

### ISSUE THREAD

**Issue by WBotzer** [zam264/CommonSquirrel#15]
Increase the game speed every 15? seconds
More aggressive obstacle generation?
Should the score increase faster as the game speed picks up?

**Comment by WBotzer** [comment]
Every 10 seconds the difficulty will increase.
1. Increase the move speed of everything (obstacles, squirrel jumps, trees, background)
2. Decrease the vertical distance between obstacles
3. Fewer health items
4. Increase the rate of distance gained as difficulty increases

**Comment by WBotzer** [comment]
Do we think the difficulty is scaling properly or should we leave this open to revisit this issue later?

**Comment by zam264** [comment]
I think it's good, I've heard comments that its scaling too quickly but we can always remedy that later when we do balancing.

Food for thought: I think it would be interesting to allow the difficulty cap to increase as your total distance increases.

So as a noob the game won't go all that fast but for a seasoned squirrel runner you can reach insane speeds.

**Comment by WBotzer** [comment]
When in space squirrel drifts not falls

**Comment by WBotzer** [comment]
Scale acorn with difficulty, change obstacles in space

**Comment by WBotzer** [comment]
Bonus score is now equal to (5 * difficulty) rounded down
