### ISSUE TITLE
Incentives

### ISSUE THREAD

**Issue by zam264** [zam264/CommonSquirrel#23]
So I think it would be good to have additional incentives for the game.

One idea could be different skins

**Comment by WBotzer** [comment]
Different skins could be pretty easy to implement, and we can take it further to apply different skins to the trees/clouds/background and all that fun stuff.  The only downside that I see is that this would require more sprites but if Casey is willing to create them I say we go for it.

**Comment by zam264** [comment]
I've been in contact with Zhou, still waiting to hear back about her eligibility to help. Once we clear that with him we can pursue this further.

**Comment by WBotzer** [comment]
Space Helmet for the squirrel

**Comment by WBotzer** [comment]
Moved to unlockable page
