### ISSUE TITLE
More friendly UI

### ISSUE THREAD

**Issue by zam264** [zam264/CommonSquirrel#25]
We can start polishing the user interface for screens like the title screen by changing things such as...
-Fonts
-Buttons (not from Dungeon Crawler)
-Transitions between scenes
-Start checking that the screens scale nicely between devices

Add to this as you think of new items

**Comment by WBotzer** [comment]
I did all the transitions

**Comment by WBotzer** [comment]
Main menu background
New buttons
Rotating when jumping
Score increase flash
Status text on score get
Score and Distance on game screen
Ground at game start
Transition background

**Comment by zam264** [comment]
DONE - Change button font
Main menu background
New buttons
Rotating when jumping
Score increase flash
DONE - Status text on score get
DONE - Score and Distance on game screen
Ground at game start
DONE - Transition background

**Comment by zam264** [comment]
DONE - Change button font
DONE - Rotating when jumping
DONE - Status text on score get
DONE - Score and Distance on game screen
DONE - Transition background
DONE - New buttons

Main menu background
Score increase flash
Ground at game start

**Comment by zam264** [comment]
Scrap score increase flash

**Comment by zam264** [comment]
DONE - Change button font
DONE - Rotating when jumping
DONE - Status text on score get
DONE - Score and Distance on game screen
DONE - Transition background
DONE - New buttons
DONE - Main menu background
DONE - Score increase flash

Ground at game start
