### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by zam264** [zam264/CommonSquirrel#26]
It wouldn't be a bad idea to include a tutorial.

Originally I included a small png at the bottom of the screen denoting the tap area for jumping trees, this should be re-done using in-game text.  

We may be able to do this with just screenshots and drawing instruction on the screenshots.

Interactive tutorials would be an option if we have time.

**Comment by zgp1001** [comment]
Definitely could be simple. Images and/ or text. Don't need a playable tutorial imo

**Comment by WBotzer** [comment]
Falling text for tutorial that changes on the type of movement
