### ISSUE TITLE
Game Crash bug caused by Pause Screen

### ISSUE THREAD

**Issue by zam264** [zam264/CommonSquirrel#27]
I discovered a bug while testing that crashes the game.

To replicate follow this procedure...
1. Play game as normal
2. Pause at any time before death
3. Select "Give Up'
4. "Play Game" again and the game will crash

The crash is for multiple reasons, all issues occur in the 'elseif' clause of the main function that runs when the application is not paused.

**Comment by WBotzer** [comment]
Fixed it, had to change an event listener
