### ISSUE TITLE
Crash on exit via pause button

### ISSUE THREAD

**Issue by zam264** [zam264/CommonSquirrel#29]
When you exit the game ('Give Up') using the pause button the game crashes at line 210 when it attempts to index global 'movementButton' (a nil value)

This also occurs when you attempt to Resume the game.  

I am assuming this is relevant to the bug @zgp1001 posted about earlier.

When swipe to move is turned off the player can resume the game but exiting the game from the pause menu still causes a crash.

**Comment by zgp1001** [comment]
Fixed it. Forgot to comment out the removal of the button that I commented out, my bad.
