### ISSUE TITLE
Jumping animation

### ISSUE THREAD

**Issue by zam264** [zam264/CommonSquirrel#3]
Animate what will eventually be jumping from tree to tree

**Comment by WBotzer** [comment]
This animation will be done in the sprite sheets and the movement will be the same transition that it is right now.

**Comment by zam264** [comment]
We may want to investigate a sort of arc movement rather than linear movement to make the action seem more realistic.  This is a low priority. 

@caseysquires can look into a side profile sprite of a squirrel jumping between trees for this animation

**Comment by zgp1001** [comment]
This is the same as sprite issue that is opened, closing this one
