### ISSUE TITLE
Vibration when hit?

### ISSUE THREAD

**Issue by zam264** [zam264/CommonSquirrel#33]
I don't know how possible this but if we have time, feedback when you hit something would be a cool addition.

**Comment by WBotzer** [comment]
system.vibrate()
You need to add in the permissions though.
This is also going to drain the user's battery and we would need another switch so we could turn this off.

**Comment by WBotzer** [comment]
Add a way to disable this in options

**Comment by zgp1001** [comment]
Added vibration and an option switch for it in options
