### ISSUE TITLE
Vibration Settings do not work

### ISSUE THREAD

**Issue by roughwood** [zam264/CommonSquirrel#63]
It seems as though at the beginning of every game, vibration is turned on. Therefore, if you disable vibration from the options menu accessed on the main menu it will not take effect and vibrate will be turned on when the game starts. If you pause mid-game and disable vibration, this works however as soon as you restart the game vibration will be on again.

**Comment by zam264** [comment]
This should be an issue with the vibration setting not being saved in the sandbox files when the user modifies the setting..

Thanks @roughwood !

**Comment by zgp1001** [comment]
The issue was with how the vibration setting was being loaded from the saved settings. Was being saved properly, but not read properly. Pushing the fix now.
