### ISSUE TITLE
Check the movement for the vibration bug

### ISSUE THREAD

**Issue by WBotzer** [zam264/CommonSquirrel#64]

**Comment by zgp1001** [comment]
Movement is fine, even tested it. 

Problem was that after reading in the settings if any of them are null (IE. first time playing the game) the setting variables are set to null (other wise we'd get errors the very first time the game is played). For vibration I was checking a variable named vibration for null, the variable name is actual vibrate - so it was always evaluating to true and setting vibrate to the default value.
