### ISSUE TITLE
Research building heights 

### ISSUE THREAD

**Issue by zam264** [zam264/CommonSquirrel#9]

**Comment by zam264** [comment]
Squirrel speed: 12MPH or 17.6ft/s

Tall stuff...
-Oak tree: 90ft
-Empire state building: 1250ft
-Football field: 360ft
-Washington monument: 555ft
-Statue of Liberty: 305ft
-Great pyramid of Giza: 455ft
-U.S. Steel Tower: 841ft
-Eiffel Tower: 986ft
-Pine Tree: 176ft
-Space Shuttle: 184ft
-Burj Khalifa (tallest building): 2717ft
-Sultan Kosen (tallest man): 8ft
-Nimitz-class aircraft carrier length: 1096ft
-Mount Everest: 29029ft

Add other interesting heights/lengths when you think of them!

**Comment by zgp1001** [comment]
I also compiled a list. I'll combine what you have with mine and post them!

**Comment by zam264** [comment]
Fantastic, also finding lengths of little stuff that can be multiplied together to get larger lengths may be interesting...

Ex. Congrats! You climbed the equivalent of 1845 candy canes!

**Comment by zgp1001** [comment]
Placed a file on the GitHub with some heights. Also started trying to name some of them since we think these are going to be "achievements". Feel free to add names and other objects (such as candy canes!)

**Comment by WBotzer** [comment]
I'm gonna close this since we have a lot of these.
